#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  2 15:03:20 2020

@author: weertman
"""

import glob
import os
import pandas
import h5py

path_dir = '/home/weertman/Documents/Theresa_FHL/Armina_DeepLabCut/test_remake_labels/image_stack/'
path_csv = glob.glob(path_dir + '*.csv')
path_images = glob.glob(path_dir + '*.png')
path_h5 = glob.glob(path_dir + '*.h5')

f = h5py.File(path_h5[0])

key = []
for k in f.keys():
    print(k)
    key.append(k)

group = f[k[0]]
data = group[k[0]].value

dat = pandas.read_csv(path_csv[0])

images_basename = path_images
n = 0

for images in path_images:
    images_basename[n] = os.path.basename(images)
    n = n + 1

n = 0
bad_rows = []
good_rows = []
for index, row in dat.iterrows():
    
    if os.path.basename(row[0]) not in images_basename:
        bad_rows.append(n)
        
    if os.path.basename(row[0]) in images_basename:
        print(os.path.basename(row[0]) + ' found')

        good_rows.append(n)
        
    n = n + 1
    
del bad_rows[0:2]

dat_new = dat.drop(dat.index[bad_rows])

pandas.DataFrame.to_csv(dat, path_csv[0])
    
    
